### ISSUE TITLE
RFC: add the cf-cli to this manifest

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/jumpbox-deployment#15]
Would you consider accepting this as a PR? As an ops file? Many people using BOSH and this release may also be administering Cloud Foundry Application runtime so it might be handy to have for many people (and a good example for how they could customize this manifest to suit their needs).

https://github.com/bosh-packages/cf-cli-release

**Comment by cppforlife** [comment]
imho jumpbox should be used for proxying connections, not to be a system from which commands run.
